//Authentication Actions
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';

//Account Actions
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_FAILED = 'FETCH_ACCOUNT_FAILED';

export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';

export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED';

//Contact Actions
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILED = 'FETCH_CONTACTS_FAILED';

export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED';

export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';

export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';

//Solicitation Actions
export const FETCH_SOLICITATIONS_SUCCESS = 'FETCH_SOLICITATIONS_SUCCESS';
export const FETCH_SOLICITATIONS_FAILED = 'FETCH_SOLICITATIONS_FAILED';

export const UPDATE_SOLICITATION_SUCCESS = 'UPDATE_SOLICITATION_SUCCESS';
export const UPDATE_SOLICITATION_FAILED = 'UPDATE_SOLICITATION_FAILED';

export const SETSCHEDULED_SOLICITATION_SUCCESS = 'SETSCHEDULED_SOLICITATION_SUCCESS';
export const SETSCHEDULED_SOLICITATION_FAILED = 'SETSCHEDULED_SOLICITATION_FAILED';

export const SETDECLINED_SOLICITATION_SUCCESS = 'SETDECLINED_SOLICITATION_SUCCESS';
export const SETDECLINED_SOLICITATION_FAILED = 'SETDECLINED_SOLICITATION_FAILED';

export const FETCH_CONTACT_NAMES_SUCCESS = 'FETCH_CONTACT_NAMES_SUCCESS';
export const FETCH_CONTACT_NAMES_FAILED = 'FETCH_CONTACT_NAMES_FAILED';

export const CREATE_SOLICITATION_SUCCESS = 'CREATE_SOLICITATION_SUCCESS';
export const CREATE_SOLICITATION_FAILED = 'CREATE_SOLICITATION_FAILED';

//Message Actions
export const FETCH_MESSAGES_SUCCESS = 'FETCH_MESSAGES_SUCCESS';
export const FETCH_MESSAGES_FAILED = 'FETCH_MESSAGES_FAILED';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';

export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_FAILED = 'UPDATE_MESSAGE_FAILED';

//Password Actions
export const CREATE_PASSWORD_RESET_SUCCESS = 'CREATE_PASSWORD_RESET_SUCCESS';
export const CREATE_PASSWORD_RESET_FAILED = 'CREATE_PASSWORD_RESET_FAILED';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

//Misc Actions
export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';